---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: goons
spec:
  schedule: "0 12 * * * "
  timeZone: "Europe/Oslo"
  startingDeadlineSeconds: 600
  successfulJobsHistoryLimit: 1
  suspend: false
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: goons
        spec:
          restartPolicy: Never
          serviceAccountName: goons-user
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            runAsUser: 65534
            runAsNonRoot: true
            runAsGroup: 65534
            fsGroup: 65534
          containers:
            - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: "{{ .Values.image.pullPolicy }}"
              name: goons
              securityContext:
                capabilities:
                  drop:
                    - ALL
                seccompProfile:
                  type: RuntimeDefault
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
              env:
                - name: FOLDERS
                  value: "{{ .Values.folderIDs }}"
                - name: RESIDENCY
                  value: "{{ .Values.residency }}"
                - name: TENANT
                  value: "{{ .Values.tenant }}"
                - name: SLACK_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      key: SLACK_API_TOKEN
                      name: slack-goons-notification
                - name: SLACK_CHANNEL
                  value: "{{ .Values.slackChannel }}"
