apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-user
  annotations:
    iam.gke.io/gcp-service-account: {{ .Release.Name }}-user@{{ .Values.projectID }}.iam.gserviceaccount.com
