environmentKinds:
  - management

values:
  folder.ids:
    displayName: Nais folder IDs
    description: Comma-separated list of folder ids to fetch findings from
    config:
      type: string
  slackWebhook:
    displayName: Slack webhook
    description: The Slack webhook to send notifications to
    config:
      type: string
