environmentKinds:
  - management

values:
  slackToken:
    displayName: Slack token
    description: The Slack token for Slack api
    config:
      type: string
      secret: true
  slackChannel:
    displayName: Slack channel
    description: The Slack channel to post findings to
    config:
      type: string
  residency:
    displayName: Data residency location
    description: The data residency of the project, ie eu or global
    config:
      type: string
  tenant:
    displayName: Tenant name
    computed:
      template: '"{{ .Tenant.Name }}"'
    config:
      type: string
  projectID:
    displayName: Google project ID
    description: The Google project ID to fetch findings from
    computed:
      template: "{{ .Env.project_id | quote }}"
    config:
      type: string
  clusters:
    displayName: Clusters project IDs
    description: Tenant clusters project IDs
    computed:
      template: |
        {{append (eachOf .Envs "project_id") .Env.project_id | join ","}}
