environmentKinds:
  - management

values:
  slackToken:
    displayName: Slack token
    description: Token for the Slack API
    config:
      type: string
      secret: true
  slackChannel:
    displayName: Slack channel
    description: The Slack channel to post findings to
    config:
      type: string
  residency:
    displayName: Data residency location
    description: The data residency of SCC findings for the tenant, i.e. eu or global
    config:
      type: string
  tenant:
    displayName: Tenant name
    computed:
      template: '"{{ .Tenant.Name }}"'
  projectID:
    displayName: Google project ID
    description: The Google project ID where the service account resides
    computed:
      template: "{{ .Env.project_id | quote }}"
  clusters:
    displayName: Clusters project IDs
    description: Tenant clusters project IDs
    computed:
      template: |
        {{append (eachOf .Envs "project_id") .Env.project_id | join ","}}
