environmentKinds:
  - management

values:
  folderIDs:
    displayName: Nais folder IDs
    description: Comma-separated list of folder ids to fetch findings from
    config:
      type: string
  slackToken:
    displayName: Slack token
    description: The Slack token for Slack api
    config:
      type: string
  projectID:
    displayName: Google project ID
    description: The Google project ID to fetch findings from
    computed:
      template: '{{ .Env.project_id | quote }}'
    config:
      type: string
  residency:
    displayName: Data residency location
    description: The data residency of the project, ie eu or global
    config:
      type: string
