environmentKinds:
  - management

values:
  organizationID:
    displayName: Organization ID
    description: The organization ID to fetch findings from
    computed:
      template: '{{ .Env.org_id | quote }}'
    config:
      type: string
  folderIDs:
    displayName: Nais folder IDs
    description: Comma-separated list of folder ids to fetch findings from
    config:
      type: string
  slackWebhook:
    displayName: Slack webhook
    description: The Slack webhook to send notifications to
    config:
      type: string
