image:
  repository: europe-north1-docker.pkg.dev/nais-io/nais/images/goons
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "main"

resources:
  cpu: 300m
  memory: 512Mi

projectID: ""